import type { Student } from '@/interfaces/student.interface';
import type { Assignment } from '@/interfaces/assignment.interface';
import type { CallLog } from '@/interfaces/callLog.interface';
import type { FollowUp } from '@/interfaces/followUp.interface';
import type { DashboardStats, StudentWithRelations } from '@/types';

export const DEMO_STUDENTS: StudentWithRelations[] = [
  {
    _id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+880 1712 345678',
    whatsapp: '+880 1712 345678',
    division: 'Dhaka',
    district: 'Dhaka',
    town: 'Mirpur',
    occupation: 'Student',
    institute: 'BUET',
    ageRange: '20-25',
    workingDevice: 'Laptop',
    currentStatus: 'Behind',
    lastCompletedAssignment: 'A-05',
    mentorshipJoiningStatus: true,
    comments: ['Struggling with time management'],
    createdAt: new Date('2024-01-15'),
  },
  {
    _id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+880 1812 654321',
    whatsapp: '+880 1812 654321',
    division: 'Chittagong',
    district: 'Chittagong',
    town: 'Nasirabad',
    occupation: 'Freelancer',
    institute: 'CU',
    ageRange: '20-25',
    workingDevice: 'Desktop',
    currentStatus: 'On Track',
    lastCompletedAssignment: 'A-08',
    mentorshipJoiningStatus: true,
    comments: [],
    createdAt: new Date('2024-01-20'),
  },
  {
    _id: '3',
    name: 'Robert Brown',
    email: 'robert@example.com',
    phone: '+880 1912 111222',
    division: 'Rajshahi',
    district: 'Rajshahi',
    occupation: 'Job Holder',
    institute: 'RU',
    ageRange: '26-30',
    workingDevice: 'Mobile',
    currentStatus: 'At Risk',
    lastCompletedAssignment: 'A-02',
    mentorshipJoiningStatus: false,
    comments: ['Health issues — gave deadline extension'],
    createdAt: new Date('2024-02-01'),
  },
  {
    _id: '4',
    name: 'Emily Chen',
    email: 'emily@example.com',
    phone: '+880 1612 999888',
    division: 'Dhaka',
    district: 'Gazipur',
    town: 'Tongi',
    occupation: 'Student',
    institute: 'DU',
    ageRange: '18-19',
    workingDevice: 'Laptop',
    currentStatus: 'On Track',
    lastCompletedAssignment: 'A-09',
    mentorshipJoiningStatus: true,
    comments: [],
    createdAt: new Date('2024-02-10'),
  },
  {
    _id: '5',
    name: 'Marcus Williams',
    email: 'marcus@example.com',
    phone: '+880 1512 777666',
    division: 'Sylhet',
    district: 'Sylhet',
    occupation: 'Business',
    ageRange: '26-30',
    workingDevice: 'Laptop',
    currentStatus: 'Behind',
    lastCompletedAssignment: 'A-03',
    mentorshipJoiningStatus: false,
    comments: ['Lost motivation, doing follow-up calls'],
    createdAt: new Date('2024-02-15'),
  },
  {
    _id: '6',
    name: 'Priya Patel',
    email: 'priya@example.com',
    phone: '+880 1712 555444',
    division: 'Dhaka',
    district: 'Narayanganj',
    occupation: 'Student',
    institute: 'NSU',
    ageRange: '20-25',
    workingDevice: 'Laptop',
    currentStatus: 'Completed',
    lastCompletedAssignment: 'A-10',
    mentorshipJoiningStatus: true,
    comments: [],
    createdAt: new Date('2024-01-10'),
  },
  {
    _id: '7',
    name: 'Amir Hossain',
    email: 'amir@example.com',
    phone: '+880 1812 333222',
    division: 'Dhaka',
    district: 'Dhaka',
    town: 'Badda',
    occupation: 'Job Holder',
    ageRange: '31-40',
    workingDevice: 'Desktop',
    currentStatus: 'At Risk',
    lastCompletedAssignment: 'A-01',
    mentorshipJoiningStatus: false,
    comments: ['Very unresponsive on calls'],
    createdAt: new Date('2024-03-01'),
  },
  {
    _id: '8',
    name: 'Sara Ahmed',
    email: 'sara@example.com',
    phone: '+880 1912 111000',
    division: 'Dhaka',
    district: 'Manikganj',
    occupation: 'Student',
    institute: 'BRACU',
    ageRange: '20-25',
    workingDevice: 'Mobile',
    currentStatus: 'On Track',
    lastCompletedAssignment: 'A-07',
    mentorshipJoiningStatus: true,
    comments: [],
    createdAt: new Date('2024-03-10'),
  },
];

export const DEMO_ASSIGNMENTS: Assignment[] = [
  {
    _id: 'a1',
    assignmentNumber: 1,
    status: 'COMPLETED',
    studentId: '1',
    completedDate: new Date('2024-02-01'),
  },
  {
    _id: 'a2',
    assignmentNumber: 2,
    status: 'COMPLETED',
    studentId: '1',
    completedDate: new Date('2024-02-08'),
  },
  {
    _id: 'a3',
    assignmentNumber: 3,
    status: 'COMPLETED',
    studentId: '1',
    completedDate: new Date('2024-02-15'),
  },
  {
    _id: 'a4',
    assignmentNumber: 4,
    status: 'COMPLETED',
    studentId: '1',
    completedDate: new Date('2024-02-22'),
  },
  {
    _id: 'a5',
    assignmentNumber: 5,
    status: 'COMPLETED',
    studentId: '1',
    completedDate: new Date('2024-03-01'),
  },
  { _id: 'a6', assignmentNumber: 6, status: 'PENDING', studentId: '1' },
  { _id: 'a7', assignmentNumber: 7, status: 'PENDING', studentId: '1' },
  { _id: 'a8', assignmentNumber: 8, status: 'PENDING', studentId: '1' },
  { _id: 'a9', assignmentNumber: 9, status: 'PENDING', studentId: '1' },
  { _id: 'a10', assignmentNumber: 10, status: 'PENDING', studentId: '1' },
];

export const DEMO_CALL_LOGS: CallLog[] = [
  {
    _id: 'cl1',
    date: new Date('2024-05-01'),
    status: 'RECEIVED',
    issues: 'Work schedule conflicts',
    promised: 'Catch up by Sunday',
    notes: 'Sounded motivated, will follow up next week.',
    calledBy: 'Mentor A',
    studentId: '1',
  },
  {
    _id: 'cl2',
    date: new Date('2024-04-20'),
    status: 'NOT_RECEIVED',
    issues: 'Health issues',
    promised: 'Back in May',
    notes: 'Second attempt. No answer.',
    calledBy: 'Mentor B',
    studentId: '3',
  },
  {
    _id: 'cl3',
    date: new Date('2024-05-03'),
    status: 'RECEIVED',
    issues: 'Lost motivation',
    promised: 'Will complete A4 and A5 this week',
    notes: 'Long call, about 25 mins. Reassured them.',
    calledBy: 'Mentor A',
    studentId: '5',
  },
  {
    _id: 'cl4',
    date: new Date('2024-05-05'),
    status: 'PHONE_OFF',
    issues: '',
    promised: '',
    notes: 'Phone was switched off both attempts.',
    calledBy: 'Mentor C',
    studentId: '7',
  },
];

export const DEMO_FOLLOW_UPS: FollowUp[] = [
  {
    _id: 'fu1',
    date: new Date('2024-05-08'),
    note: 'Check if John completed A6 after our last call.',
    studentId: '1',
  },
  {
    _id: 'fu2',
    date: new Date('2024-05-10'),
    note: 'Marcus promised A4 and A5 done. Verify and motivate.',
    studentId: '5',
  },
  {
    _id: 'fu3',
    date: new Date('2024-05-12'),
    note: 'Try Robert again — third attempt.',
    studentId: '3',
  },
];

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  totalStudents: 8,
  activeStudents: 7,
  onTrackStudents: 3,
  atRiskStudents: 3,
  completedStudents: 1,
  totalAssignments: 80,
  pendingAssignments: 42,
  completedAssignments: 38,
  totalCallLogs: 4,
  totalFollowUps: 3,
  pendingFollowUps: 3,
};
